[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xd18616"
index = 16

[[colors.indexed_colors]]
color = "0xf97583"
index = 17

[colors.bright]
black = "0x959da5"
blue = "0x79b8ff"
cyan = "0x56d4dd"
green = "0x85e89d"
magenta = "0xb392f0"
red = "0xf97583"
white = "0xfafbfc"
yellow = "0xffea7f"

[colors.cursor]
cursor = "0xffcc1b"
text = "0x002635"

[colors.normal]
black = "0x586069"
blue = "0x2188ff"
cyan = "0x39c5cf"
green = "0x34d058"
magenta = "0xb392f0"
red = "0xea4a5a"
white = "0xd1d5da"
yellow = "0xffea7f"

[colors.primary]
background = "0x24292e"
foreground = "0xd1d5da"

[cursor.style]
shape = "Block"

[font]
size = 11.0

[font.bold]
family = "monospace"

[font.normal]
family = "monospace"
style = "Regular"

[window]
decorations = "none"
decorations_theme_variant = "Dark"
startup_mode = "Maximized"
